server:
  port: 8888
#account db
spring:
  datasource:
   accountdb:
    jdbcUrl : jdbc:mysql://localhost:3306/account_db?createDatabaseIfNotExist=true
    username : root
    password : root
    driver-class-name : com.mysql.cj.jdbc.Driver
   userdb:
    jdbcUrl : jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
    username : root
    password : root
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      
 